# Generated by Django 2.2.14 on 2020-08-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cvitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvitem',
            name='to_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
