# Generated by Django 2.2.14 on 2020-08-27 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_cvitem_to_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvitem',
            old_name='section',
            new_name='title',
        ),
    ]
